spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: postgres  # ? ????? ??? ??????
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ????????????? ???????/????????? ??????? ??? ???????
    show-sql: true      # ?????????? SQL-??????? ? ??????? (??????? ??? ???????)
    properties:
      hibernate:
        format_sql: true      # ??????? ??????????? SQL
        dialect: org.hibernate.dialect.PostgreSQLDialect  # ??????? Hibernate, ??? ?? ???????? ? PostgreSQL
    open-in-view: false

  thymeleaf:
    cache: false         # ????????? ??????????? ???????? (????? ?????? ????????? ?????)
    prefix: classpath:/templates/
    suffix: .html

  devtools:
    restart:
      enabled: true      # ???????????????? ??? ????????? ????
    livereload:
      enabled: true      # ????????????? ????????? ???????? ? ????????

  servlet:
    multipart:
      max-file-size: 5MB   # ??? ???????? ???????? (????? ??????????)
      max-request-size: 5MB

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: INFO
    com.marketplace: DEBUG  # ???? ????? ??????????

# Настройки загрузки файлов
file:
  upload-dir: uploads/products/